### ISSUE TITLE
Rename routes to /push and /pop

### ISSUE THREAD

**Issue by shubjain26** [Nimish5/Queue-Implementation-Using-Flask#3]
Instead of /add_hobbies and /del_hobbies change  it to /push and /pop.

**Comment by Nimish5** [comment]
kk... Thank you, will do the specified changes. But while changing I will
not be able to change it in the repository, I have to change the code in my
system then again have to upload it in the GitHub.

Thanks,

**Comment by shubjain26** [comment]
update the code in local repository


git add {filename}
git commit 
git push
